general:
 cut_seq: GCGC
 genome: mm10
 pu1_motif: AGGAGT
 max_cpgs: 10
 n_imcs: 300

input:
 type: bed

sample_annotation:
 sampleID: sampleID
 bw_file: bw_file
 cov_file: cov_file
 cell_type: cell_type

rnbeads:
 sampleID: sampleID
 coverage: 10
 cell_type: cell_type
 assembly: mm10

dmcs:
 number: 500
 methylated: 0.95
 unmethylated: 0.05
 number_meth_unmeth: 100
 coverage_threshold: 10
 min_diff: 0.2

non_cut:
 n_amplicons: 75
 max_cpgs: 20
 length: 400
 n_cgis: 10
 n_promoters: 18
 n_genes: 24
 none: 23
 min_gc: 0.40
 max_gc: 0.50

annotations:
 tf_chip: /users/mscherer/cluster/project/Methylome/src/selection_pipeline/annotations/TFBS_Wilson/bed/mm10/
 enhancer_catalog: /users/mscherer/cluster/project/Methylome/src/selection_pipeline/annotations/enhancer_catalog_Lara_Astiaso_Science/H3K27Ac.csv
 #Please download the file 'H3K27Ac_mm10.bed' from https://www.science.org/doi/10.1126/science.1256271 and put it to the folder 'annotations'
 enhancer_catalog_bed: /users/mscherer/cluster/project/Methylome/src/selection_pipeline/annotations/enhancer_catalog_Lara_Astiaso_Science/H3K27Ac_mm10.bed
 #Please download the file 'GSM774291_FLDN1PU.1I.bb' from https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM774291, process it with bedtools and liftover to convert it into mm10
 pu1_chip: /users/mscherer/cluster/project/Methylome/src/selection_pipeline/annotations/ZhangChIP/GSM774291_FLDN1PU.1I_mm10.bed
 hema_tf_motifs: /users/mscherer/cluster/project/Methylome/src/selection_pipeline/annotations/TFBS_motifs/TFBSs.csv
 variable_genes: /users/mscherer/cluster/project/Methylome/src/selection_pipeline/annotations/variable_genes_Nestorowa2015.csv
 aging_dmcs: /users/mscherer/cluster/project/Methylome/src/selection_pipeline/annotations/aging_dmrs.csv
