library(RnBeads)
theme_set(theme_bw())
xml.file <- "/users/lvelten/project/Methylome/src/selection_pipeline/RnBeads/Yu2016/rnbOptions.xml"
arch <- new("ClusterArchitectureSGE")
arch <- setExecutable(arch,"R","/users/lvelten/mscherer/conda/envs/rnbeads/bin/R")
arch <- setExecutable(arch,"Rscript","/users/lvelten/mscherer/conda/envs/rnbeads/bin/Rscript")
rnb.cr <- new("RnBClusterRun",arch)
rnb.cr <- setModuleResourceRequirements(rnb.cr,c(h_vmem="80G",virtual_free="80G",h_rt="05:00:00"),"all")
rnb.cr <- setModuleNumCores(rnb.cr,1L,"all")
rnb.cr <- setModuleNumCores(rnb.cr,1L,"exploratory")
run(rnb.cr, "rnB_Yu", xml.file, queue="short-sl7")
